# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Hitshaskell
tagline:          'A blog for Haskell'
description:      'A place to think Haskell'
url:              https://hitscotty.github.io/hitshaskell
baseurl:          /hitshaskell/

author:
  name:           'Jonathan Portorreal'
  url:            https://twitter.com/hitscotty

# Custom vars
version:          Scotty
github:
  repo:           https://github.com/hitscotty

# Gems
gems: [jekyll-paginate, jekyll-gist, redcarpet, pygments.rb]

paginate: 5
paginate_path: "page:num"
